### ISSUE TITLE
name property from FirebaseToken is null

### ISSUE THREAD

**Issue by grrigore** [plusmobileapps/ktor-firebase-auth-sample#2]
I don't know if I missed something but in my case `it.name` is null from 

```
fun Application.configureFirebaseAuth() {
    install(Authentication) {
        firebase {
            validate {
                // TODO look up user profile from DB
                User(it.uid, it.name)
            }
        }
    }
}
```

I followed the tutorial and came across that. I am using email/password signup this might be the case of the error.

**Comment by plusmobileapps** [comment]
Is it just the name property that is null? Or is it the whole firebase user object that is null? If uid isn't null it could just be that the user you are authenticating with doesn't have a name so you could fix it with .orEmpty()

**Comment by grrigore** [comment]
`name` is null. Yes, it seems the user doesn't have a name (`name` is not in the list of properties of the FirebaseToken I receive). However, I wonder if it worked for you using email/password auth.

**Comment by plusmobileapps** [comment]
@grrigore it does work for me with email password, but I was using my personal account logging into a personal project on firebase which I know has a name. I'll have to update the project to account for this and use the orEmpty() function or make the user name property itself null. 

Not sure which sdk you are using, but in my project to add a name to the email password can be done with the [update profile api](https://firebase.google.com/docs/reference/rest/auth#section-update-profile) once you have the access token.

**Comment by grrigore** [comment]
I've used [Sign up with email/password](https://firebase.google.com/docs/reference/rest/auth#section-create-email-password) to create an account and there was no name set. I'll try to use that update profile endpoint. Thank you for your time and great tutorial! :)
